### ISSUE TITLE
DemoServiceGrpc.java:20: error: cannot find symbol

### ISSUE THREAD

**Issue by debayandesarkar** [phiSgr/gatling-grpc-gradle-demo#1]
Hi,
Thanks for sharing this repo. I am getting the below error during build. Can you please help?

➜  gatling-grpc-gradle-demo-master ./gradlew run                                                

> Task :compileJava FAILED
/opt/GitHub/gatling-grpc-gradle-demo-master/build/generated/source/proto/main/grpc/com/github/phisgr/example/DemoServiceGrpc.java:20: error: cannot find symbol
@javax.annotation.Generated(
                 ^
  symbol:   class Generated
  location: package javax.annotation
1 error
![image](https://user-images.githubusercontent.com/38543344/115947138-84729800-a47a-11eb-8972-5e7b0f025175.png)

Regards
Debayan

**Comment by phiSgr** [comment]
Try using Java 8.
