### ISSUE TITLE
Intellij not prompting the event log message

### ISSUE THREAD

**Issue by mrinal-sharma** [phiSgr/gatling-grpc-gradle-demo#3]
Hello, I am using the Gatling-JavaPb library but unfortunately, IntelliJ is not prompting the message in the event log. Is there any workaround to that? Please let me know

**Comment by phiSgr** [comment]
What do you see in the IntelliJ preferences?

<img width="706" alt="Screenshot 2021-07-29 at 12 51 59" src="https://user-images.githubusercontent.com/13439232/127533108-62ae6f25-f000-4d36-bc5e-8fb6d9ed3767.png">

**Comment by mrinal-sharma** [comment]
<img width="900" alt="Screen Shot 2021-07-29 at 9 56 21 AM" src="https://user-images.githubusercontent.com/88157297/127533530-73e696a3-dc36-453b-bd21-0447e130e0ae.png">

**Comment by phiSgr** [comment]
Try to download this and load it with the "+" button.
https://repo1.maven.org/maven2/com/github/phisgr/gatling-javapb-ijext/1.1.0/gatling-javapb-ijext-1.1.0.jar

**Comment by mrinal-sharma** [comment]
Thank you so much, it is working now.
